<?php
declare(strict_types=1);

// Airtable SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

AirtableUtility::setRegistrar(function (AirtableUtility $u): void {
    $u->clean = [AirtableClean::class, 'call'];
    $u->done = [AirtableDone::class, 'call'];
    $u->make_error = [AirtableMakeError::class, 'call'];
    $u->feature_add = [AirtableFeatureAdd::class, 'call'];
    $u->feature_hook = [AirtableFeatureHook::class, 'call'];
    $u->feature_init = [AirtableFeatureInit::class, 'call'];
    $u->fetcher = [AirtableFetcher::class, 'call'];
    $u->make_fetch_def = [AirtableMakeFetchDef::class, 'call'];
    $u->make_context = [AirtableMakeContext::class, 'call'];
    $u->make_options = [AirtableMakeOptions::class, 'call'];
    $u->make_request = [AirtableMakeRequest::class, 'call'];
    $u->make_response = [AirtableMakeResponse::class, 'call'];
    $u->make_result = [AirtableMakeResult::class, 'call'];
    $u->make_point = [AirtableMakePoint::class, 'call'];
    $u->make_spec = [AirtableMakeSpec::class, 'call'];
    $u->make_url = [AirtableMakeUrl::class, 'call'];
    $u->param = [AirtableParam::class, 'call'];
    $u->prepare_auth = [AirtablePrepareAuth::class, 'call'];
    $u->prepare_body = [AirtablePrepareBody::class, 'call'];
    $u->prepare_headers = [AirtablePrepareHeaders::class, 'call'];
    $u->prepare_method = [AirtablePrepareMethod::class, 'call'];
    $u->prepare_params = [AirtablePrepareParams::class, 'call'];
    $u->prepare_path = [AirtablePreparePath::class, 'call'];
    $u->prepare_query = [AirtablePrepareQuery::class, 'call'];
    $u->graphql_body = [AirtableGraphql::class, 'body'];
    $u->graphql_errors = [AirtableGraphql::class, 'errors'];
    $u->result_basic = [AirtableResultBasic::class, 'call'];
    $u->result_body = [AirtableResultBody::class, 'call'];
    $u->result_headers = [AirtableResultHeaders::class, 'call'];
    $u->transform_request = [AirtableTransformRequest::class, 'call'];
    $u->transform_response = [AirtableTransformResponse::class, 'call'];
});
